### ISSUE TITLE
How to get this to work?

### ISSUE THREAD

**Issue by MastaBaba** [BrowseHandsfree/handsfreeJS#19]
I just created a simple page like so:

```
<!DOCTYPE html>
<html>
<body>

<script src="https://unpkg.com/handsfree@2.0.3"></script>

<script>
	const handsfree = new Handsfree({debug: true})
	handsfree.start()
</script>

</body>
</html>
```

This results in:

[Error] TypeError: null is not an object (evaluating 'this.debug.$wrap.style')
	toggleDebugger (handsfree.js:9:138505)
	start (handsfree.js:9:132305)
	Global Code (index.php:9)

Nothing happens in the page.

How do I get this to work?

**Comment by labofoz** [comment]
Hi, thanks for giving this a try and sorry for the delay! I goofed up in 2.0.3...you need to have a `.handsfree-debug-wrap` which is where the video/canvas get injected into. I need to update the docs, and I plan on adding simple example files like the one you included.

For now try this:

```html
<!DOCTYPE html>
<html>
<body>
<div class="handsfree-debug-wrap"></div>


<script src="https://unpkg.com/handsfree@2.1.0"></script>

<script>
	const handsfree = new Handsfree({debug: true})
	handsfree.start()
</script>

</body>
</html>
```

You'll notice that the canvas isn't lined up properly (which I'll also fix) but everything else will work. Thanks again for reporting this!

**Comment by MastaBaba** [comment]
Thanks. This works indeed. It's looking good.

Note that this works for me in Firefox, but Safari hangs after about a second.

**Comment by labofoz** [comment]
Hey thanks again for giving this a shot, I ended up doing a huge refactor. I'm going to close this issue for now and open up a new one for Safari as I'm going to hand that off to a friend to fix.

This issue also inspired me to do more small demos and improve the documentation, so I appreciate you opening the issue (and I apologize for taking so long to respond)
